services:
  uptime-kuma:
    image: louislam/uptime-kuma:1
    ports:
      - '127.0.0.1:3002:3001'
    container_name: uptime-kuma
    restart: unless-stopped
    volumes:
      - ./uptime:/app/data
      - /var/run/docker.sock:/var/run/docker.sock
        #    labels:
        #      caddy: uptime-kuma.foodshare.club
        #      caddy.reverse_proxy: "* {{upstreams 3002}}"
    networks:
      #      - no-zero-trust-cloudflared
      #      - zero-trust-cloudflared
      #      - web
      - remnawave-network

  uptime-kuma-cleanup:
    image: keinos/sqlite3
    container_name: uptime-kuma-cleanup
    volumes:
      - ./uptime:/app/data
    user: "0:0"  # Run as root
    command: >
      /bin/sh -c '
      echo "*/30 * * * * sqlite3 /app/data/kuma.db \"
        DELETE FROM heartbeat WHERE time < datetime('\''now'\'', '\''-7 days'\'');
        DELETE FROM notification_sent_history WHERE time < datetime('\''now'\'', '\''-7 days'\'');
        DELETE FROM incident_history WHERE time < datetime('\''now'\'', '\''-10 days'\'');
        DELETE FROM monitor_tls_info WHERE time < datetime('\''now'\'', '\''-7 days'\'');
        DELETE FROM status_page_heartbeat WHERE time < datetime('\''now'\'', '\''-7 days'\'');
        VACUUM;
        PRAGMA wal_checkpoint(TRUNCATE);
      \"" > /etc/crontabs/root &&
      crond -f -d 8
      '


networks:
  remnawave-network:
    external: true
    name: remnawave-network   

      #networks:
      #  web:
      #    external: true
      #    name: web
      #  no-zero-trust-cloudflared:
      #    external: true
      #    driver: bridge
      #    name: no-zero-trust-cloudflared
      #  zero-trust-cloudflared:
      #    external: true
      #    name: zero-trust-cloudflared

volumes:
  caddy_data:
    external: true
  caddy:
    external: true
  caddy_config:
  tls:
    external: true
  vault-data:
    external: true
