/**
 * Latency trend for a single monitor.
 *
 * Lives in TypeScript rather than a `.wgsl` file because Turbopack has no
 * loader for `.wgsl` ("Unknown module type"), and this string is the exact
 * value handed to `effect()`. `__tests__/lib/gpu-shaders.test.ts` writes it to
 * a temp file and runs `vgpu check` against it, so the shader that ships is
 * the shader that is validated.
 *
 * The vertex stage is generated by vgpu (a fullscreen triangle), so only a
 * fragment entry point is supplied.
 *
 * Coordinate space: `uv` is normalised to 0..1 with the origin at the bottom
 * left, and storage samples carry the same normalised space. Comparing raw
 * `fragCoord` pixels against normalised sample positions collapses the
 * polyline into a corner, so the resolution is an explicit uniform.
 */
export const latencyTrendShader = /* wgsl */ `
struct Params {
  count: f32,
  time: f32,
  resolution: vec2f,
  padding: vec2f,
};

struct Sample {
  position: vec2f,
  status: f32,
  padding: f32,
};

@group(0) @binding(0) var<uniform> params: Params;
@group(0) @binding(1) var<storage, read> samples: array<Sample>;

fn statusTint(status: f32) -> vec3f {
  if (status < 0.5) { return vec3f(0.937, 0.267, 0.267); }
  if (status < 1.5) { return vec3f(0.063, 0.725, 0.506); }
  if (status < 2.5) { return vec3f(0.965, 0.627, 0.043); }
  if (status < 3.5) { return vec3f(0.259, 0.596, 0.965); }
  return vec3f(0.976, 0.686, 0.180);
}

@fragment
fn fs_main(@builtin(position) fragCoord: vec4f) -> @location(0) vec4f {
  let resolution = max(params.resolution, vec2f(1.0, 1.0));
  let uv = vec2f(fragCoord.x / resolution.x, 1.0 - fragCoord.y / resolution.y);

  var color = vec3f(0.043, 0.043, 0.063);

  let grid = max(
    step(0.97, fract(uv.x * 20.0)),
    step(0.97, fract(uv.y * 8.0))
  );
  color = mix(color, vec3f(0.129, 0.129, 0.161), grid * 0.45);

  let count = i32(params.count);
  if (count < 2) {
    return vec4f(color, 1.0);
  }

  // Aspect-corrected so the stroke keeps an even weight on wide surfaces.
  let aspect = resolution.x / resolution.y;

  for (var i = 0; i < count - 1; i = i + 1) {
    let a = samples[i];
    let b = samples[i + 1];

    // Everything below happens in aspect-corrected space, where distances are
    // isotropic. Mixing corrected and uncorrected terms here breaks the
    // projection and leaves the polyline visibly dotted.
    let p = vec2f(uv.x * aspect, uv.y);
    let pa = vec2f(a.position.x * aspect, a.position.y);
    let pb = vec2f(b.position.x * aspect, b.position.y);

    let seg = pb - pa;
    let lenSq = max(dot(seg, seg), 1e-6);
    let t = clamp(dot(p - pa, seg) / lenSq, 0.0, 1.0);
    let dist = length(p - (pa + seg * t));

    // A segment takes the worse of its two endpoints, so a single degraded
    // check marks both the segment leaving it and the segment returning to it.
    let tint = statusTint(max(a.status, b.status));
    color = mix(color, tint, (1.0 - smoothstep(0.0015, 0.0055, dist)) * 0.95);
  }

  let last = samples[count - 1];
  let pulse = 0.5 + 0.5 * sin(params.time * 3.0);
  let headDist = length(vec2f(uv.x * aspect, uv.y) - vec2f(last.position.x * aspect, last.position.y));
  color = mix(color, statusTint(last.status), (1.0 - smoothstep(0.006, 0.016, headDist)) * (0.45 + 0.55 * pulse));

  return vec4f(color, 1.0);
}
`;
